"""
Synthetic Financial Transaction Data Generator

This script creates a synthetic transaction dataset for the
AI Financial Crime Investigator project.

The generated data contains:
    1. Normal transactions
    2. Suspicious fan-out patterns
    3. Layering patterns
    4. Circular transaction patterns
    5. Rapid movement of funds

Because we generate the suspicious behavior ourselves, we know
the ground truth. This allows us to evaluate our ML model later.

IMPORTANT:
    All data generated by this script is synthetic.
    It does not represent real people, accounts, or financial activity.
"""

# ============================================================
# 1. IMPORT LIBRARIES
# ============================================================

import random
from datetime import datetime, timedelta

import numpy as np
import pandas as pd


# ============================================================
# 2. CONFIGURATION
# ============================================================

# Number of synthetic accounts to create.
NUM_ACCOUNTS = 1000

# Number of normal transactions to generate.
NUM_NORMAL_TRANSACTIONS = 10000

# Number of suspicious patterns to generate.
# Each pattern can create multiple transactions.
NUM_SUSPICIOUS_PATTERNS = 100

# Random seed makes the generated dataset reproducible.
# If we run the script again, we get the same data.
RANDOM_SEED = 42

random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)


# ============================================================
# 3. CREATE ACCOUNT IDs
# ============================================================

# Generate account IDs such as:
# A0001, A0002, A0003, ..., A1000

accounts = [
    f"A{i:04d}"
    for i in range(1, NUM_ACCOUNTS + 1)
]


# ============================================================
# 4. HELPER FUNCTION — RANDOM TIMESTAMP
# ============================================================

# Our synthetic transactions will occur over a 30-day period.

START_DATE = datetime(2026, 1, 1)
END_DATE = datetime(2026, 1, 30)


def random_timestamp(start=START_DATE, end=END_DATE):
    """
    Generate a random timestamp between start and end.
    """

    time_difference = end - start

    random_seconds = random.randint(
        0,
        int(time_difference.total_seconds())
    )

    return start + timedelta(seconds=random_seconds)


# ============================================================
# 5. HELPER FUNCTION — RANDOM TRANSACTION AMOUNT
# ============================================================

def random_amount():
    """
    Generate a realistic-looking transaction amount.

    We use a log-normal distribution instead of a simple
    uniform distribution because financial transaction
    amounts are usually not evenly distributed.
    """

    amount = np.random.lognormal(
        mean=5.5,
        sigma=1.0
    )

    # Keep amounts within a reasonable synthetic range.
    amount = max(10, min(amount, 100000))

    return round(amount, 2)


# ============================================================
# 6. TRANSACTION STORAGE
# ============================================================

# Every transaction will eventually be stored in this list.

transactions = []

# Used to create unique transaction IDs.
transaction_counter = 1


def add_transaction(
    sender,
    receiver,
    amount,
    timestamp,
    transaction_type,
    pattern_type,
    is_suspicious
):
    """
    Add one transaction to our dataset.

    Parameters:
        sender            -> sending account
        receiver         -> receiving account
        amount            -> transaction amount
        timestamp         -> transaction date/time
        transaction_type  -> type of transaction
        pattern_type      -> behavioral pattern
        is_suspicious     -> ground-truth label
    """

    global transaction_counter

    transactions.append({
        "transaction_id": f"T{transaction_counter:07d}",
        "sender_id": sender,
        "receiver_id": receiver,
        "amount": round(amount, 2),
        "timestamp": timestamp,
        "transaction_type": transaction_type,

        # This tells us what kind of behavior generated
        # the transaction.
        "pattern_type": pattern_type,

        # Ground-truth label.
        #
        # 0 = normal
        # 1 = intentionally generated as suspicious
        #
        # This will NOT be used forever. Later, we can
        # hide/remove this column when testing the ML model.
        "is_suspicious": is_suspicious
    })

    transaction_counter += 1


# ============================================================
# 7. GENERATE NORMAL TRANSACTIONS
# ============================================================

print("Generating normal transactions...")

for _ in range(NUM_NORMAL_TRANSACTIONS):

    # Randomly select two different accounts.
    sender, receiver = random.sample(accounts, 2)

    # Generate a normal transaction.
    amount = random_amount()

    timestamp = random_timestamp()

    # Select a normal transaction type.
    transaction_type = random.choice([
        "transfer",
        "payment",
        "salary",
        "purchase"
    ])

    add_transaction(
        sender=sender,
        receiver=receiver,
        amount=amount,
        timestamp=timestamp,
        transaction_type=transaction_type,
        pattern_type="normal",
        is_suspicious=0
    )


# ============================================================
# 8. SUSPICIOUS PATTERN — FAN-OUT
# ============================================================

def generate_fan_out():
    """
    Generate a fan-out pattern.

    One account sends money to many different accounts.

    Example:

        A0500 → A0601
        A0500 → A0602
        A0500 → A0603
        A0500 → A0604

    This can represent a synthetic example of funds
    being distributed across multiple accounts.
    """

    # Choose the central account.
    source = random.choice(accounts)

    # Select several different receiving accounts.
    receivers = random.sample(accounts, random.randint(4, 8))

    base_time = random_timestamp()

    for i, receiver in enumerate(receivers):

        add_transaction(
            sender=source,
            receiver=receiver,
            amount=random.uniform(1000, 10000),

            # Transactions happen close together.
            timestamp=base_time + timedelta(
                minutes=i * random.randint(1, 10)
            ),

            transaction_type="transfer",
            pattern_type="fan_out",
            is_suspicious=1
        )


# ============================================================
# 9. SUSPICIOUS PATTERN — LAYERING
# ============================================================

def generate_layering():
    """
    Generate a multi-step transaction chain.

    Example:

        A0100 → A0200 → A0300 → A0400 → A0500

    The money passes through multiple intermediary accounts.
    """

    # Create a chain of 4–6 accounts.
    chain = random.sample(
        accounts,
        random.randint(4, 6)
    )

    base_amount = random.uniform(5000, 20000)

    base_time = random_timestamp()

    for i in range(len(chain) - 1):

        sender = chain[i]
        receiver = chain[i + 1]

        # Slightly reduce the amount at each step.
        # This creates a more realistic flow where the
        # transferred amount changes along the chain.
        amount = base_amount * (1 - i * 0.02)

        add_transaction(
            sender=sender,
            receiver=receiver,
            amount=amount,

            # Each transfer happens shortly after the previous one.
            timestamp=base_time + timedelta(
                minutes=i * random.randint(5, 20)
            ),

            transaction_type="transfer",
            pattern_type="layering",
            is_suspicious=1
        )


# ============================================================
# 10. SUSPICIOUS PATTERN — CIRCULAR FLOW
# ============================================================

def generate_circular_flow():
    """
    Generate a circular transaction pattern.

    Example:

        A0100 → A0200
                 ↓
        A0400 ← A0300
          ↑
          └────────

    More simply:

        A100 → A200 → A300 → A400 → A100

    The money eventually returns to the starting account.
    """

    # Choose 4 different accounts.
    cycle = random.sample(accounts, 4)

    base_amount = random.uniform(3000, 15000)

    base_time = random_timestamp()

    for i in range(len(cycle)):

        sender = cycle[i]

        # The next account is the receiver.
        # The last account sends money back to the first.
        receiver = cycle[(i + 1) % len(cycle)]

        add_transaction(
            sender=sender,
            receiver=receiver,
            amount=base_amount * random.uniform(0.95, 1.05),

            timestamp=base_time + timedelta(
                minutes=i * random.randint(5, 15)
            ),

            transaction_type="transfer",
            pattern_type="circular_flow",
            is_suspicious=1
        )


# ============================================================
# 11. SUSPICIOUS PATTERN — RAPID MOVEMENT OF FUNDS
# ============================================================

def generate_rapid_movement():
    """
    Generate a pattern where an account receives money
    and quickly sends it somewhere else.

    Example:

        A100 → A200    $10,000
        A200 → A300     $9,800   (2 minutes later)

    This creates a rapid pass-through behavior.
    """

    # Choose three different accounts.
    sender, intermediary, receiver = random.sample(accounts, 3)

    base_time = random_timestamp()

    amount = random.uniform(5000, 20000)

    # First transaction enters the intermediary account.
    add_transaction(
        sender=sender,
        receiver=intermediary,
        amount=amount,
        timestamp=base_time,
        transaction_type="transfer",
        pattern_type="rapid_movement",
        is_suspicious=1
    )

    # Second transaction leaves the intermediary very quickly.
    add_transaction(
        sender=intermediary,
        receiver=receiver,
        amount=amount * random.uniform(0.95, 0.99),
        timestamp=base_time + timedelta(
            minutes=random.randint(1, 5)
        ),
        transaction_type="transfer",
        pattern_type="rapid_movement",
        is_suspicious=1
    )


# ============================================================
# 12. GENERATE SUSPICIOUS PATTERNS
# ============================================================

print("Generating suspicious transaction patterns...")

for _ in range(NUM_SUSPICIOUS_PATTERNS):

    # Randomly select which suspicious behavior to create.
    pattern = random.choice([
        "fan_out",
        "layering",
        "circular_flow",
        "rapid_movement"
    ])

    if pattern == "fan_out":
        generate_fan_out()

    elif pattern == "layering":
        generate_layering()

    elif pattern == "circular_flow":
        generate_circular_flow()

    elif pattern == "rapid_movement":
        generate_rapid_movement()


# ============================================================
# 13. CONVERT TRANSACTIONS INTO A DATAFRAME
# ============================================================

df = pd.DataFrame(transactions)


# ============================================================
# 14. SORT TRANSACTIONS BY TIME
# ============================================================

# Sorting makes the dataset easier to analyze later.

df = df.sort_values(
    by="timestamp"
).reset_index(drop=True)


# ============================================================
# 15. SAVE THE DATASET
# ============================================================

# Save the generated data inside the data/ folder.

output_path = "data/transactions.csv"

df.to_csv(
    output_path,
    index=False
)


# ============================================================
# 16. PRINT DATASET SUMMARY
# ============================================================

print("\n========================================")
print("Synthetic dataset generated successfully!")
print("========================================")

print(f"Total transactions: {len(df):,}")
print(f"Unique accounts: {NUM_ACCOUNTS:,}")

print(
    f"Suspicious transactions: "
    f"{df['is_suspicious'].sum():,}"
)

print(
    f"Normal transactions: "
    f"{(df['is_suspicious'] == 0).sum():,}"
)

print("\nPattern distribution:")
print(
    df["pattern_type"]
    .value_counts()
)

print(f"\nDataset saved to: {output_path}")

print("\nFirst 10 transactions:")
print(
    df.head(10).to_string(index=False)
)
